/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#ffdea7",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-dim": "#d9dadc",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed": "#2f1500",
        "on-background": "#191c1e",
        "surface-container-high": "#e7e8ea",
        "on-secondary-container": "#785500",
        "tertiary": "#884800",
        "background": "#f8f9fb",
        "outline": "#787586",
        "surface-variant": "#e1e2e4",
        "surface-tint": "#5847d2",
        "inverse-on-surface": "#f0f1f3",
        "secondary-fixed-dim": "#f0bf63",
        "on-primary-container": "#faf6ff",
        "surface-bright": "#f8f9fb",
        "on-tertiary-fixed-variant": "#6e3900",
        "on-primary-fixed": "#160066",
        "on-tertiary-container": "#fff5f1",
        "surface": "#f8f9fb",
        "primary-fixed": "#e4dfff",
        "tertiary-fixed-dim": "#ffb77d",
        "on-primary-fixed-variant": "#4029ba",
        "on-secondary-fixed-variant": "#5e4200",
        "secondary-container": "#ffcd70",
        "primary": "#5341cd",
        "outline-variant": "#c8c4d7",
        "on-surface-variant": "#474554",
        "primary-fixed-dim": "#c6bfff",
        "tertiary-container": "#ac5d00",
        "on-secondary": "#ffffff",
        "inverse-primary": "#c6bfff",
        "on-surface": "#191c1e",
        "surface-container": "#edeef0",
        "on-primary": "#ffffff",
        "primary-container": "#6c5ce7",
        "error-container": "#ffdad6",
        "secondary": "#7c5800",
        "surface-container-highest": "#e1e2e4",
        "tertiary-fixed": "#ffdcc3",
        "on-secondary-fixed": "#271900",
        "inverse-surface": "#2e3132"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "lg": "var(--radius)",
        "md": "calc(var(--radius) - 2px)",
        "sm": "calc(var(--radius) - 4px)",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
}
